#! /usr/bin/env python
#

import sys
from argparse import ArgumentParser

from g2remote import g2connect


main = g2connect.main

if __name__ == '__main__':

    argprs = ArgumentParser(description="connect to Gen2 remote screens")

    argprs.add_argument("--debug", dest="debug", default=False, action="store_true",
                        help="Enter the pdb debugger on main()")
    argprs.add_argument("-f", "--config", dest="config", metavar="FILE",
                        help="Read configuration from FILE")
    argprs.add_argument("--profile", dest="profile", action="store_true",
                        default=False,
                        help="Run the profiler on main()")
    argprs.add_argument("-v", "--version", dest="showversion",
                        action="store_true",
                        help="Show g2remote version")
    (options, args) = argprs.parse_known_args(sys.argv[1:])

    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('main(options, args)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print("%s profile:" % sys.argv[0])
        profile.run('main(options, args)')

    else:
        main(options, args)
